List gazpromListData = [];
List allData = [];

newAllData() {
  gazpromListData = [];
  allData = [];
  allData = [...gazpromPrice, ...genergyPrice, ...kroonPrice, ...priorPrice];
  for (var item in allData) {
    gazpromListData.add(item['name']);
  }
}

List gazpromPrice = [
  {
    "name": "Cutfluid Standard",
    "price": [
      '20L - 150 azn',
    ],
    'type': 'Soyutma mayesi',
    'image': 'https://iili.io/GmbGgR.png',
    'characteristic': 'Смазочно-охлаждающая жидкость',
    'description':
        'Gazpromneft Cutfluid Standard – высококачественная водосмешиваемая жидкость с высоким содержанием минерального масла и высокоэффективным пакетом присадок, обеспечивающими многофункциональность и стабильность эмульсии. Рекомендуемая концентрация – 3-8% в зависимости от режима обработки конкретного металла',
    'use':
        'Для обработки шлифованием, точением, нарезкой, сверлением и фрезерованием всех типов сталей, алюминия, цветных металлов и чугуна.',
    'test':
        '- Высокие смазывающие свойства -\n Высокая антикоррозионная защита -\n Экономичность в использовании -\n Легко смешивается с водой -\n Долгий срок службы эмульсии -\n Хорошая стабильность эмульсии -\n Используется для воды широкого диапазона жесткости (100-500 ррм) -\n Продукт безопасен для окружающей среды\nВязкость кинематическая при 40°С, мм2/с - ГОСТ 33 - 31,2\nПлотность при 20°С, кг/м³ - ГОСТ 3900 - 889\nВодородный показатель, 5% эмульсии, рН, в пределах - ГОСТ 6243 п.4 - 9.0',
  },
  {
    "name": "Cutfluid Universal",
    "price": [
      '20L - 200 azn',
    ],
    'type': 'Soyutma mayesi',
    'image': 'https://iili.io/Gmbhbt.png',
    'characteristic': 'Смазочно-охлаждающая жидкость',
    'description':
        'Gazpromneft Cutfluid Universal – полусинтетическая водосмешиваемая жидкость широкого спектра применения с содержанием минерального масла. Концентрат обеспечивает многофункциональность и стабильность эмульсии даже при экстремальных режимах обработки металла. Рекомендуемая концентрация – 3-8% в зависимости от режима обработки и обрабатываемого металла. Коэффициент рефракции = 1.2',
    'use':
        'Продукт разработан для большинства операций металлообработки: шлифования, точения, резки, сверления и фрезерованием. Рекомендуется для различных черных металлов, включая сталь и чугун, алюминия и его сплавов, цветных металлов.',
    'test':
        '- Эффективная антикоррозионная защита -\n Превосходное удаление металлической стружки -\n Высокие охлаждающие свойства -\n Экономичность в использовании -\n Легко смешивается с водой -\n Долгий срок службы эмульсии -\n Отличная стабильность мелкодисперсной структуры эмульсии -\n Подходит для воды широкого диапазона жесткости -\n Продукт безопасен для окружающей среды\nВязкость кинематическая при 40°С, мм2/с - ГОСТ 33 - 44,4\nПлотность при 20°С, кг/м³ - ГОСТ 3900 - 981\nВодородный показатель, 5% эмульсии, рН, в пределах - ГОСТ 6243 п.4 - 9.1',
  },
  {
    "name": "PS Fluid",
    "price": [
      '1L - 5 azn',
    ],
    'type': 'Sükan mayesi',
    'image': 'https://iili.io/Gkqa6u.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "PREMIUM A3 5W30",
    "price": [
      '1L - 7 azn',
      '4L - 26 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkqQSf.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "PREMIUM JK 5W30",
    "price": [
      '1L - 8 azn',
      '4L - 28 azn',
      '205L - 1100 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gkqk8v.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "PREMIUM L 5W40",
    "price": [
      '1L - 7 azn',
      '4L - 26 azn',
      '5L - 32 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkBfAQ.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "PREMIUM N 5W40",
    "price": [
      '1L - 8 azn',
      '4L - 29 azn',
      '5L - 35 azn',
      '205L - 1200 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkBuUJ.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "SUPER 10W40",
    "price": [
      '1L - 5.5 azn',
      '4L - 18 azn',
      '5L - 22 azn',
      '20L - 85 azn',
      '205L - 830 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkB7Np.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "SUPER 15W40",
    "price": [
      '1L - 4.5 azn',
      '4L - 16 azn',
      '5L - 21 azn',
      '205L - 830 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkBlVt.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "STANDART 15W40",
    "price": [
      '1L - 4.5 azn',
      '4L - 16 azn',
      '5L - 21 azn',
      '205L - 750 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkBMUG.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "STANDART 20W50",
    "price": [
      '1L - 4.8 azn',
      '4L - 17 azn',
      '5L - 21 azn',
      '205L - 750 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkBZqF.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Premium L 10W40",
    "price": [
      '1L - 6 azn',
      '4L - 22 azn',
      '5L - 26 azn',
      '205L - 950 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkCJzN.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Premium L 15W40",
    "price": [
      '1L - 5.5 azn',
      '4L - 18 azn',
      '5L - 23 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkCFqX.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Disel Premium 10W40",
    "price": [
      '5L - 28 azn',
      '20L - 110 azn',
      '30L - 155 azn',
      '205L - 980 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkCfgs.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Disel Premium 15W40",
    "price": [
      '20L - 105 azn',
      '30L - 150 azn',
      '205L - 950 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkCR1e.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Disel Prioritet 10W30",
    "price": [
      '205L - 900 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkCYdb.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Diesel Prioritet 10W40",
    "price": [
      '20L - 100 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkCVB1.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Diesel Prioritet 15W40",
    "price": [
      '5L - 25 azn',
      '20L - 95 azn',
      '30L - 138 azn',
      '205L - 880 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkCNkv.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Diesel Extra 10W40",
    "price": [
      '1L - 5.5 azn',
      '5L - 25 azn',
      '20L - 95 azn',
      '205L - 870 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkCvhN.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Diesel Extra 15W40",
    "price": [
      '1L - 5.5 azn',
      '5L - 24 azn',
      '20L - 90 azn',
      '30L - 125 azn',
      '205L - 800 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkCQTl.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Diesel Extra 20W50",
    "price": [
      '5L - 24 azn',
      '20L - 90 azn',
      '30L - 125 azn',
      '205L - 800 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkCtQS.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Diesel Extra 50",
    "price": [
      '5L - 25 azn',
      '30L - 140 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gkn93u.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Turbo Universal 15W40",
    "price": [
      '4L - 18 azn',
      '5L - 22 azn',
      '10L - 44 azn',
      '20L - 85 azn',
      '30L - 120 azn',
      '205L - 750 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gkndyx.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Diesel Ultra 15W40",
    "price": [
      '20L - 105 azn',
      '205L - 970 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GknKZB.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Turbo Universal 20W50",
    "price": [
      '5L - 23 azn',
      '10L - 45 azn',
      '20L - 88 azn',
      '30L - 125 azn',
      '205L - 770 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GknhnS.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "M-10 DM",
    "price": [
      '4L - 17 azn',
      '5L - 21 azn',
      '10L - 42 azn',
      '20L - 80 azn',
      '30L - 115 azn',
      '205L - 700 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkzOFt.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "M-10Q2K",
    "price": [
      '4L - 17 azn',
      '5L - 21 azn',
      '10L - 40 azn',
      '20L - 75 azn',
      '30L - 110 azn',
      '205L - 700 azn',
    ],
    'type': 'Yay mühərrik yağı',
    'image': 'https://iili.io/Gkz6V2.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "HD-40",
    "price": [
      '1L - 5 azn',
      '4L - 17 azn',
      '5L - 22 azn',
      '10L - 43 azn',
      '20L - 80 azn',
      '30L - 120 azn',
      '205L - 750 azn',
    ],
    'type': 'Yay mühərrik yağı',
    'image': 'https://iili.io/GkztHu.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "HD-50",
    "price": [
      '1L - 5 azn',
      '4L - 17 azn',
      '5L - 22 azn',
      '10L - 44 azn',
      '20L - 85 azn',
      '30L - 120 azn',
      '205L - 750 azn',
    ],
    'type': 'Yay mühərrik yağı',
    'image': 'https://iili.io/GkzmDx.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "HD-60",
    "price": [
      '20L - 88 azn',
      '30L - 120 azn',
      '205L - 750 azn',
    ],
    'type': 'Yay mühərrik yağı',
    'image': 'https://iili.io/GkIRJn.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Motor Oil 40",
    "price": [
      '1L - 4.5 azn',
      '4L - 16 azn',
      '5L - 20 azn',
      '20L - 75 azn',
      '205L - 720 azn',
    ],
    'type': 'Yay mühərrik yağı',
    'image': 'https://iili.io/GkIEfS.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Motor Oil 50",
    "price": [
      '1L - 4.5 azn',
      '4L - 16 azn',
      '5L - 20 azn',
      '20L - 75 azn',
      '205L - 750 azn',
    ],
    'type': 'Yay mühərrik yağı',
    'image': 'https://iili.io/GkIesV.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Motor Oil 60",
    "price": [
      '1L - 4.5 azn',
      '4L - 16 azn',
      '5L - 20 azn',
      '20L - 82 azn',
      '205L - 720 azn',
    ],
    'type': 'Yay mühərrik yağı',
    'image': 'https://iili.io/GkI6mJ.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "I-20 A",
    "price": [
      '5L - 19 azn',
      '20L - 70 azn',
      '205L - 650 azn',
    ],
    'type': 'Sənaye yağı',
    'image': 'https://iili.io/GkIt1I.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "I-40 A",
    "price": [
      '5L - 19 azn',
      '10L - 37 azn',
      '20L - 70 azn',
      '205L - 650 azn',
    ],
    'type': 'Sənaye yağı',
    'image': 'https://iili.io/GkImdX.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "I-50 A",
    "price": [
      '205L - 650 azn',
    ],
    'type': 'Sənaye yağı',
    'image': 'https://iili.io/GkTgG2.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "SRUS-4",
    "price": [
      '100qr - 3 azn',
      '150qr - 4 azn',
      '300qr - 6.5 azn',
      '400qr - 9.7 azn',
    ],
    'type': 'Sürtkü yağı',
    'image': 'https://iili.io/GkuT9n.jpg',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "LITOL-24",
    "price": [
      '100qr - 2 azn',
      '150qr - 2.5 azn',
      '300qr - 4 azn',
      '350qr - 4.5 azn',
      '400qr - 6 azn',
      '800qr - 10 azn',
      '4kg - 45 azn',
      '8kg - 88 azn',
      '18kg - 185 azn',
      '45kg - 450 azn',
      '170kg - 1500 azn',
    ],
    'type': 'Sürtkü yağı',
    'image': 'https://iili.io/GkuYMl.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "EP-2",
    "price": [
      '800qr - 12 azn',
      '18kg - 195 azn',
      '170kg - 1850 azn',
    ],
    'type': 'Sürtkü yağı',
    'image': 'https://iili.io/GkujMQ.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "EP-3",
    "price": [
      '18kg - 210 azn',
    ],
    'type': 'Sürtkü yağı',
    'image': 'https://iili.io/Gku4ov.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "GREASE L EP 00",
    "price": [
      '18kg - 130 azn',
    ],
    'type': 'Sürtkü yağı',
    'image': 'https://iili.io/GkuDRn.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "GREASE LX EP-2",
    "price": [
      '400qr - 6 azn',
      '4kg - 50 azn',
    ],
    'type': 'Sürtkü yağı',
    'image': 'https://iili.io/GkAdf2.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "HIDRAVLIK-32",
    "price": [
      '20L - 78 azn',
    ],
    'type': 'Hidravlika yağı',
    'image': 'https://iili.io/GkAoWx.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "HIDRAVLIK MQE-46B",
    "price": [
      '4L - 16 azn',
      '20L - 75 azn',
      '205L - 680 azn',
    ],
    'type': 'Hidravlika yağı',
    'image': 'https://iili.io/GkA55F.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "HIDRAVLIK MQE-68",
    "price": [
      '20L - 75 azn',
      '205L - 680 azn',
    ],
    'type': 'Hidravlika yağı',
    'image': 'https://iili.io/GkAG0N.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "HIDRAVLIK HLP-32",
    "price": [
      '20L - 80 azn',
    ],
    'type': 'Hidravlika yağı',
    'image': 'https://iili.io/GkAX5X.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "HIDRAVLIK HLP-46",
    "price": [
      '10L - 42 azn',
      '20L - 80 azn',
      '205L - 750 azn',
    ],
    'type': 'Hidravlika yağı',
    'image': 'https://iili.io/GkAvql.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "HIDRAVLIK HLP-68",
    "price": [
      '20L - 80 azn',
      '205L - 750 azn',
    ],
    'type': 'Hidravlika yağı',
    'image': 'https://iili.io/GkAr79.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "HIDRAVLIK HVLP-46",
    "price": [
      '205L - 950 azn',
    ],
    'type': 'Hidravlika yağı',
    'image': 'https://iili.io/GkRdhJ.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "HIDRAVLIK HVLP-68",
    "price": [
      '205L - 950 azn',
    ],
    'type': 'Hidravlika yağı',
    'image': 'https://iili.io/GkRK1p.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "VMQZ (ВМГЗ)",
    "price": [
      '205L - 690 azn',
    ],
    'type': 'Hidravlika yağı',
    'image': 'https://iili.io/M4r6L7.png',
    'characteristic': 'ВМГЗ, ВМГЗ ПАО',
    'description':
        'Всесезонные гидравлические масла, производящиеся на высокоочищенной маловязкой основе. Содержат эффективные пакеты присадок, обеспечивающие необходимые вязкостные, антиокислительные, противоизносные, антикоррозионные, низкотемпературные и антипенные свойства. Масло Газпромнефть ВМГЗ ПАО содержит синтетический компонент, что обеспечивает лучшие эксплуатационные характеристики в сравнении с аналогичными маслами других производителей. В процессе работы масла практически исключено падение его вязкости за счет деструкции загущающих присадок. Гарантирует надежную эксплуатацию гидравлических машин в интервале температур от -30°С до +50 °С, в зависимости от типа гидронасоса. Масло Газпромнефть ВМГЗ обеспечивает надежную эксплуатацию гидравлических машин в климатических условиях России (от -25 до +50°С, в зависимости от типа гидронасоса).\nПреимущества\n - Отличные вязкостно-температурные свойства обеспечивают безотказную работу оборудования в широком диапазоне температур\n - Защищают детали гидросистемы от износа и коррозии\n - Высокая окислительная и химическая стабильность обеспечивают длительную работу масел в гидросистеме\n - Отличная фильтруемость',
    'use':
        'Для систем гидропривода и гидроуправления строительных, дорожных, лесозаготовительных, подъемнотранспортных и других машин, работающих на открытом воздухе.',
    'test':
        'Вязкость кинематическая при 50 °С, мм2 /с - ГОСТ 33 - 14 - 11,5\nВязкость динамическая, мПа·с: при -25 °С, при -30 °С - ASTM D 5293 ASTM D 5293-10 - 1200 - 1749\nТемпература вспышки в открытом тигле, °С - ГОСТ 4333 - 195 - 200\nТемпература застывания, °С - ГОСТ 20287 -46 -48\nКислотное число, мг KOH/г - ГОСТ 11362 - 0,4 - 0,4\nПлотность при 20 °С, кг/м3 - ASTM D 4052 - 865 - 854',
  },
  {
    "name": "M-14Г2ЦС",
    "price": [
      '205L - 690 azn',
    ],
    'type': 'Gəmi yağı',
    'image': 'https://iili.io/GkRaY7.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "M-16Г2ЦС",
    "price": [
      '205L - 800 azn',
    ],
    'type': 'Gəmi yağı',
    'image': 'https://iili.io/GkRaY7.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "М-14 B2",
    "price": [
      '205L - 720 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkRaY7.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Industrial 40",
    "price": [
      '205L - 650 azn',
    ],
    'type': 'Sənaye yağı',
    'image': 'https://iili.io/GkRNv1.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "МГД-20 М",
    "price": [
      '205L - 950 azn',
    ],
    'type': 'İki taktlı qaz\nmühərriki kompressorları',
    'image': 'https://iili.io/GkRaY7.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Rubber Оil",
    "price": [
      '205L - 870 azn',
    ],
    'type': 'Texniki yağ',
    'image': 'https://iili.io/GkRaY7.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "XA-30",
    "price": [
      '180kg - 980 azn',
    ],
    'type': 'Soyuducu yağ',
    'image': 'https://iili.io/GkRaY7.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Moto 2T",
    "price": [
      '1L - 5 azn',
      '4L - 17 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gk7lWb.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Moto 4T 10W40",
    "price": [
      '1L - 6 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gk7WdB.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Moto 4T 20W50",
    "price": [
      '1L - 6 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gk7Sgp.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "SUPER T-2 75W90 GL-4",
    "price": [
      '1L - 11 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://iili.io/GkYJIe.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "SUPER T-2 80W90 GL-4",
    "price": [
      '1L - 6 azn',
      '4L - 21 azn',
      '5L - 25 azn',
      '10L - 50 azn',
      '20L - 95 azn',
      '205L - 930 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://iili.io/GkYcvI.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "SUPER T-2 80W90 GL-5",
    "price": [
      '1L - 6 azn',
      '20L - 100 azn',
      '205L - 950 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://iili.io/GkYvje.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "GL-5 140",
    "price": [
      '1L - 6.5 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://iili.io/Gka29I.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "GL-4 140",
    "price": [
      '1L - 6 azn',
      '4L - 21 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://iili.io/Gka7ou.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "GL-5 85W140",
    "price": [
      '1L - 6 azn',
      '20L - 105 azn',
      '205L - 930 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://iili.io/Gkahog.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "TSp-15 K",
    "price": [
      '4L - 20 azn',
      '10L - 50 azn',
      '205L - 820 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://iili.io/Gk8xLb.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "GL-1 90",
    "price": [
      '20L - 87 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://iili.io/Gk8GEv.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "KS-19p A",
    "price": [
      '10L - 50 azn',
      '205L - 820 azn',
    ],
    "type": 'Kompressor yağı',
    'image': 'https://iili.io/Gk8XYN.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Compressor Oil–46 VCL",
    "price": [
      '20L - 110 azn',
    ],
    "type": 'Kompressor yağı',
    'image': 'https://iili.io/Gk8eQs.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Compressor\n S.Synth–46 VDL",
    "price": [
      '20L - 115 azn',
      '205L - 1050 azn',
    ],
    "type": 'Kompressor yağı',
    'image': 'https://iili.io/Gk8m3Q.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "ATF DX II",
    "price": [
      '1L - 6 azn',
      '4L - 23 azn',
      '20L - 90 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://iili.io/GkS9yP.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "ATF DX III",
    "price": [
      '1L - 8 azn',
      '4L - 28 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://iili.io/GkSBFR.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Reductor CLP-68",
    "price": [
      '20L - 90 azn',
    ],
    'type': 'Reduktor yağı',
    'image': 'https://iili.io/GkSx9I.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Reductor CLP-150",
    "price": [
      '20L - 90 azn',
      '205L - 850 azn',
    ],
    'type': 'Reduktor yağı',
    'image': 'https://iili.io/GkS8DF.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Reductor CLP-220",
    "price": [
      '20L - 95 azn',
      '205L - 850 azn',
    ],
    'type': 'Reduktor yağı',
    'image': 'https://iili.io/GkS6Kv.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "TURBIN Tp-22 C",
    "price": [
      '205L - 650 azn',
    ],
    'type': 'Turbin yağı',
    'image': 'https://iili.io/GkSQRI.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Turbine Oil 32",
    "price": [
      '205L - 650 azn',
    ],
    'type': 'Turbin yağı',
    'image': 'https://iili.io/GkSQRI.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "AdBlue",
    "price": [
      '20L - 26 azn',
    ],
    'type': 'Reagent',
    'image': 'https://iili.io/GkU2J2.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Antifreeze BS 40",
    "price": [
      '1kg - 3.2 azn',
      '5kg - 14 azn',
      '10kg - 30 azn',
      '220kg - 650 azn',
    ],
    'type': 'Soyuducu maye',
    'image': 'https://iili.io/GkUqxe.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Antifreeze SF 12+ premix",
    "price": [
      '1kg - 3.2 azn',
      '5kg - 14 azn',
    ],
    'type': 'Soyuducu maye',
    'image': 'https://iili.io/GkUBWu.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Antifreeze consentrat BS tasol 40",
    "price": [
      '1kg - 3 azn',
      '5kg - 13 azn',
      '10kg - 23 azn',
      '220kg - 950 azn',
    ],
    'type': 'Soyuducu maye',
    'image': 'https://iili.io/GkUx0x.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "MOTOR YUYAN Promo",
    "price": [
      '3.5L - 14 azn',
    ],
    'type': 'Motor yuyan',
    'image': 'https://iili.io/GkUe1f.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "SUPER DOT-4",
    "price": [
      '455qr - 2.2 azn',
    ],
    'type': 'Əyləc mayesi',
    'image': 'https://iili.io/GkUD7V.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
];

List genergyPrice = [
  {
    "name": "G-Energy Far East 0W20",
    "price": [
      '1L - 10 azn',
      '4L - 36 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkgBpI.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Energy Far East 5W30",
    "price": [
      '1L - 8 azn',
      '4L - 30 azn',
      '5L - 36 azn',
      '50L - 380 azn',
      '205L - 1500 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkgohX.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Energy Far East 5W20",
    "price": [
      '1L - 10 azn',
      '4L - 38 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkgR24.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Energy FE DX 1 5W30",
    "price": [
      '1L - 11 azn',
      '4L - 40 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkgcT7.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Energy F Synth 5W30",
    "price": [
      '4L - 48 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkgGEb.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Energy F Synth EC 5W30",
    "price": [
      '1L - 11 azn',
      '4L - 38 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkgXYQ.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Energy F Synth 5W40",
    "price": [
      '1L - 11 azn',
      '4L - 40 azn',
      '5L - 50 azn',
      '50L - 420 azn',
      '205L - 1750 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkgeZF.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Energy Synthetic Super Star 5W30",
    "price": [
      '1L - 11 azn',
      '4L - 40 azn',
      '50L - 420 azn',
      '205L - 1750 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkgraR.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Energy Expert L 5W30",
    "price": [
      '1L - 8 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gkg4vp.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Energy Synthetic Active 5W40",
    "price": [
      '1L - 8 azn',
      '4L - 30 azn',
      '5L - 36 azn',
      '50L - 330 azn',
      '205L - 1350 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gk4YX9.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Energy Expert L 5W40",
    "price": [
      '1L - 8 azn',
      '4L - 29 azn',
      '5L - 34 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gk4FON.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Energy Synthetic\nLong Life 10W40",
    "price": [
      '1L - 9 azn',
      '4L - 33 azn',
      '5L - 42 azn',
      '50L - 350 azn',
      '205L - 1350 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gk4M5Q.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Energy Expert L 10W40",
    "price": [
      '1L - 7 azn',
      '4L - 25 azn',
      '5L - 30 azn',
      '50L - 260 azn',
      '205L - 980 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gk4wLF.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Energy Expert G 10W40",
    "price": [
      '1L - 6 azn',
      '4L - 22 azn',
      '5L - 28 azn',
      '205L - 950 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gk4e1a.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Energy Expert G 15W40",
    "price": [
      '1L - 6 azn',
      '4L - 20 azn',
      '5L - 24 azn',
      '205L - 850 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gk4PLX.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Energy Expert G 20W50",
    "price": [
      '1L - 6 azn',
      '4L - 20 azn',
      '5L - 24 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gk4D74.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Profi MSI 10W30",
    "price": [
      '205L - 1200 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gk62Eu.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Profi MSI 10W40",
    "price": [
      '20L - 125 azn',
      '205L - 1200 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gk6ICF.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Profi MSI Plus 15W40",
    "price": [
      '50L - 300 azn',
      '205L - 1200 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gk6Ypp.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Profi MSH 15W40",
    "price": [
      '205L - 1150 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gk6GGn.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Profi MSF 10W40",
    "price": [
      '20L - 115 azn',
      '205L - 1050 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gk6Nu2.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Profi MSK 15W40",
    "price": [
      '20L - 160 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/Gk6S6u.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "TO-4 10W",
    "price": [
      '20L - 120 azn',
    ],
    'type': 'Hidravlika yağı',
    'image': 'https://iili.io/Gk6raj.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "TO-4 10W30",
    "price": [
      '20L - 125 azn',
    ],
    'type': 'Hidravlika yağı',
    'image': 'https://iili.io/GkPBFs.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Profi MSF 15W40",
    "price": [
      '20L - 115 azn',
      '205L - 1050 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkPx94.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Profi MSJ 15W40",
    "price": [
      '30L - 175 azn',
      '205L - 1600 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://iili.io/GkPeHv.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Special Hydravlic HVLP-46",
    "price": [
      '205L - 1350 azn',
    ],
    'type': 'Hidravlika yağı',
    'image': 'https://iili.io/GkPtb2.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Box Expert\nGL-4 75W90",
    "price": [
      '1L - 13 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://iili.io/GkPmW7.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Box Expert GL-5 80W90",
    "price": [
      '1L - 7 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://iili.io/Gki35x.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Box ATF Far East Italiya",
    "price": [
      '1L - 13 azn',
      '4L - 50 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://iili.io/GkiBWP.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Box ATF Far East",
    "price": [
      '4L - 38 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://iili.io/GkiBWP.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Box Expert ATF DX III",
    "price": [
      '1L - 9 azn',
      '4L - 32 azn',
      '20L - 150 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://iili.io/Gki7zN.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Box ATF DX III Italiya",
    "price": [
      '4L - 46 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://iili.io/GkiYXI.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Box ATF DX VI",
    "price": [
      '1L - 12 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://iili.io/Gki01n.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Energy Expert DOT-4",
    "price": [
      '455qr - 70 azn',
    ],
    'type': 'Əyləc mayesi',
    'image': 'https://iili.io/Gkie1e.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Energy Antifreeze 40",
    "price": [
      '1kg - 3.5 azn',
      '5kg - 17 azn',
      '10kg - 30 azn',
      '220kg - 650 azn',
    ],
    'type': 'Soyuducu maye',
    'image': 'https://iili.io/Gkikru.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "G-Energy Antifreeze Consentrant",
    "price": [
      '220kg - 950 azn',
    ],
    'type': 'Soyuducu mayesi',
    'image': 'https://iili.io/Gki4IV.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
];

List kroonPrice = [
  {
    "name": "HELAR SP 0W-30",
    "price": [
      '1L - 22 azn',
      '5L - 110 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/32302.png',
    'characteristic': 'VW 503.00/506.00/506.01',
    'description':
        'Helar SP 0W-30 — полностью синтетическое топливоэкономичное моторное масло, изготовленное на основе синтетических базовых масел с высоким индексом вязкости. Helar SP 0W-30 содержит современные присадки, созданные по новейшим технологиям, которые обеспечивают продукту следующие свойства:\n - снижение расхода топлива\n - очень высокий индекс вязкости и высокая прочность на сдвиг\n - беспроблемный холодных запуск\n - защитная смазочная пленка, сохраняющаяся при очень высоких рабочих температурах\n - высокие диспергирующие и моющие свойства\n - очень высокая степень защиты от износа, коррозии и вспенивания',
    'use':
        'Helar SP 0W-30 – топливоэкономичное синтетическое моторное масло, специально разработанное для легковых автомобилей Volkswagen с увеличенным интервалом замены масла. Helar SP 0W-30 можно также использовать в 4-тактных бензиновых и дизельных двигателях. Правила использования см. в технических характеристиках продукта в листе технических данных.',
    'test':
        ' - Плотность при 15 °C, кг/л = 0,856\n - Вязкость при -35 °C, мПа∙с = 5580\n - Вязкость при 40 °C, мм²/с	= 53,00\n - Вязкость при 100 °C, мм²/с = 9,60\n - Индекс вязкости = 165\n - Температура вспышки по Кливленду, °C = 215\n - Температура застывания, °C	= -39\n - Общее щелочное число, мг KOH/г = 10,0\n - Кислотное число, мг KOH/г = 3,37\n - Сульфатная зольность, % = 1,28\n - Летучесть по Noack, % = 9,5',
  },
  {
    "name": "AVANZA MSP 5W-30",
    "price": [
      '1L - 12 azn',
      '4L - 45 azn',
      '5L - 55 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/36703.png',
    'characteristic': 'ACEA C2 PSA B71 2290',
    'description':
        'Avanza MSP+ 5W-30 — современное синтетическое топливосберегающее моторное масло Mid-SAPS, разработанное по новейшим технологиям для автомобилей c сажевыми фильтрами и/или каталитическими нейтрализаторами. Специальные синтетические базовые масла и присадки обеспечивают следующие свойства:\n - снижение расхода топлива\n - превосходная защита от преждевременного воспламенения\n - снижение образования продуктов сгорания благодаря более низкому содержанию SAPS\n - повышение срока службы сажевых фильтров и каталитических нейтрализаторов\n - беспроблемный холодный запуск\n - защитная смазочная пленка при высоких температурах\n - увеличенные интервалы замены\n - превосходные диспергирующие и моющие свойства\n - очень высокая степень защиты от износа, коррозии и вспенивания',
    'use':
        'Avanza MSP+ 5W-30 предназначено для бензиновых и дизельных двигателей автомобилей c сажевым фильтром и/или каталитическим нейтрализатором. Специальная формула Mid-SAPS обеспечивает увеличенный срок службы. Это масло также обеспечивает превосходную защиту от преждевременного воспламенения смеси в цилиндрах. Подходит для использования в автомобилях PSA, требующих моторное масло спецификации PSA B71 2290 > 2017, а также во всех автомобилях, которым предписаны моторные масла по спецификации ACEA C2.',
    'test':
        '\n - Плотность при 15 °C, кг/л = 0,849\n - Вязкость при -30 °C, мПа∙с = 4130\n - Вязкость при 40 °C, мм²/с = 50,90\n - Вязкость при 100 °C, мм²/с = 9,64\n - Индекс вязкости = 178\n - Температура вспышки по Кливленду, °C = 224\n - Температура застывания, °C = -42\n - Общее щелочное число, мг KOH/г = 6,6\n - Сульфатная зольность, % = 0,51\n - Летучесть по Noack, % = 12,2',
  },
  {
    "name": "PRESTEZA MSP 5W-30",
    "price": [
      '1L - 12 azn',
      '4L - 45 azn',
      '5L - 55 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/35137.png',
    'characteristic':
        'ACEA C2, C3, API SN, BMW Longlife-04, MB-Approval 229.51/229.52, MB 229.31, GM dexos 2, Opel OV0401547, VW 505.00/505.01',
    'description':
        'Presteza MSP 5W-30 — синтетическое топливоэкономичное моторное масло для автомобилей последнего поколения, оснащенных сажевыми фильтрами и/или каталитическими нейтрализаторами. Специальные технологии по обеспечению Mid SAPS обеспечивают увеличенный срок службы. В продукт добавлены специально подобранные базовые масла и современные присадки, обеспечивающие следующие свойства:\n - снижение расхода топлива\n - снижение уровня образования продуктов сгорания благодаря среднему уровню сульфатной зольности и содержанию фосфора и серы (Mid SAPS)\n - беспроблемный холодных запуск\n - защитная смазочная пленка при высоких рабочих температурах\n - увеличенные интервалы замены масла\n - высокие диспергирующие и моющие свойства\n - очень высокая степень защиты от износа, коррозии и вспенивания',
    'use':
        'Presteza MSP 5W-30 – синтетическое топливоэкономичное моторное масло. Пригодно для бензиновых и дизельных двигателей легковых автомобилей и фургонов. По требованию производителя интервалы между заменой масла можно увеличить. Продукт соответствует требованиям Mid SAPS Mercedes-Benz (MB 229.51) и BMW (BMW LL-04). Идеально подходит для новейших моделей BMW и Mercedes, оснащенных сажевым фильтром, и для всех автомобилей, для которых требуется моторное масло ACEA C3.',
    'test':
        '\n - Плотность при 15 °C, кг/л = 0,855\n - Вязкость при -30 °C, мПа∙с = 6160\n - Вязкость при 40 °C, мм²/с = 74,40\n - Вязкость при 100 °C, мм²/с = 12,30\n - Индекс вязкости = 168\n - Температура вспышки по Кливленду, °C = 228\n - Температура застывания, °C = -45\n - Общее щелочное число, мг KOH/г = 7,7\n - Сульфатная зольность, % = 0,80\n - Летучесть по Noack, % = 9,5',
  },
  {
    "name": "MEGANZA LSP 5W-30",
    "price": [
      '1L - 12 azn',
      '5L - 55 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/35686.png',
    'characteristic': 'ACEA C3, C4, MB 229.51/226.51, Renault RN0720',
    'description':
        'Meganza LSP 5W-30 — современное синтетическое топливоэкономичное моторное масло по новейшим технологиям обеспечения низкого уровня SAPS. Идеально для автомобилей с сажевыми фильтрами и/или каталитическими нейтрализаторами. Специальный подбор синтетических базовых масел и современных присадок обеспечил следующие свойства:\n - снижение расхода топлива\n - снижение уровня образования продуктов сгорания благодаря сниженному уровню сульфатной зольности и содержанию фосфора и серы\n - повышение срока службы сажевых фильтров и каталитических нейтрализаторов\n - беспроблемный холодных запуск\n - защитная смазочная пленка при высоких рабочих температурах\n - увеличенные интервалы замены масла\n - высокие диспергирующие и моющие свойства\n - очень высокая степень защиты от износа, коррозии и вспенивания',
    'use':
        'Meganza LSP 5W-30 специально разработано для современных бензиновых и дизельных двигателей легковых автомобилей и фургонов с сажевым фильтром и/или каталитическим нейтрализатором. Специальная формула Low SAPS обеспечивает увеличенный срок службы. По требованию производителя интервалы между заменой масла можно увеличить. Подходит для новейших моделей Renault, оснащенных дизельным сажевым фильтром, и для всех автомобилей других марок, которые должны соответствовать спецификации ACEA C4.',
    'test':
        '\n - Плотность при 15 °C, кг/л = 0,851\n - Вязкость при -30 °C, мПа∙с = 6320\n - Вязкость при 40 °C, мм²/с = 72,80\n - Вязкость при 100 °C, мм²/с = 12,40\n - Индекс вязкости = 170\n - Температура вспышки по Кливленду, °C = 216\n - Температура застывания, °C = -39\n - Общее щелочное число, мг KOH/г = 6,6\n - Сульфатная зольность, % = 0,49\n - Летучесть по Noack, % = 8,7',
  },
  {
    "name": "Poly Tech 5w30",
    "price": [
      '1L - 20 azn',
      '5L - 90 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/35467.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Poly Tech 5w40",
    "price": [
      '1L - 20 azn',
      '5L - 90 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/36140.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Emperol 5w40",
    "price": [
      '1L - 10 azn',
      '4L - 40 azn',
      '5L - 47 azn',
      '60L - 500 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/33217.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Specialisynth MSP 5w40",
    "price": [
      '1L - 12 azn',
      '4L - 45 azn',
      '5L - 55 azn',
      '60L - 500 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/35213.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Kroontrak Super 10w30",
    "price": [
      '20L - 140 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/34445.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Emperol Diesel 10w40",
    "price": [
      '1L - 9 azn',
      '4L - 32 azn',
      '5L - 40 azn',
      '20L - 145 azn',
      '60L - 410 azn',
      '208L - 1320 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/35654.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Emperol 10w40",
    "price": [
      '1L - 9 azn',
      '4L - 32 azn',
      '5L - 40 azn',
      '20L - 145 azn',
      '60L - 410 azn',
      '208L - 1320 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/33216.png',
  },
  {
    "name": "Synfleet SHPD 10w40",
    "price": [
      '20L - 165 azn',
      '60L - 460 azn',
      '208L - 1420 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/02333.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Emperol Racing 10w60",
    "price": [
      '1L - 15 azn',
      '4L - 60 azn',
      '5L - 70 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/34347.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Multifleet SHPD 10w40",
    "price": [
      '20L - 140 azn',
      '200L - 1320 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/10065.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Bi-Turbo 15w40",
    "price": [
      '1L - 7 azn',
      '4L - 30 azn',
      '5L - 33 azn',
      '20L - 130 azn',
      '60L - 370 azn',
      '208L - 1250 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/33078.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Bi-Turbo 20w50",
    "price": [
      '1L - 7 azn',
      '4L - 30 azn',
      '5L - 33 azn',
      '20L - 130 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/33079.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Multifleet SHPD 15w40",
    "price": [
      '5L - 37 azn',
      '20L - 135 azn',
      '60L - 400 azn',
      '208L - 1300 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/00331.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Multifleet SHPD 20w50",
    "price": [
      '5L - 35 azn',
      '20L - 135 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/00332.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Dieselfleet CD+ 15w40",
    "price": [
      '20L - 145 azn',
      '208L - 1400 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/35439.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Dieselfleet MSP 15w40",
    "price": [
      '20L - 180 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/35951.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Torsynth 5w30",
    "price": [
      '1L - 11 azn',
      '4L - 40 azn',
      '5L - 48 azn',
      '208L - 1500 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/32643.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Torsynth 5w40",
    "price": [
      '1L - 9 azn',
      '4L - 35 azn',
      '5L - 43 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/36169.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Gearlube HS GL-5 75w90",
    "price": [
      '20L - 180 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/35077.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Gearlube GL-5 80w90",
    "price": [
      '1L - 10 azn',
      '20L - 180 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/01325.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Gearlube GL-5 85w140",
    "price": [
      '5L - 37 azn',
      '20L - 140 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/01329.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "ATF Dexron II-D",
    "price": [
      '1L - 6 azn',
      '5L - 37 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/01324.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "ATF SP 2024",
    "price": [
      '1L - 15 azn',
      '5L - 220 azn',
    ],
    'image': '',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "ATF SP 4016",
    "price": [
      '1L - 17 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': '',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "SP Matic 4026",
    "price": [
      '1L - 17 azn',
      '5L - 75 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/32378.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "SP Matic 4036",
    "price": [
      '1L - 16 azn',
      '5L - 75 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/36750.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "SP MATIC 2032",
    "price": [
      '1L - 16 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/02230.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Atf sp 2092",
    "price": [
      '1L - 14 azn',
      '20L - 240 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': '',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Almirol ATF",
    "price": [
      '1L - 12 azn',
      '5L - 55 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/01322.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "ATF SP Matic 2082",
    "price": [
      '1L - 17 azn',
      '20L - 200 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': '',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Perlus H 32",
    "price": [
      '20L - 130 azn',
    ],
    'type': 'Hidravlika yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/02314.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Perlus H 46",
    "price": [
      '20L - 130 azn',
      '208L - 1150 azn',
    ],
    'type': 'Hidravlika yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/31091.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Perlus H 68",
    "price": [
      '20L - 110 azn',
      '60L - 330 azn',
    ],
    'type': 'Hidravlika yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/31092.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Antifreeze",
    "price": [
      '1L - 9 azn',
    ],
    'type': 'Soyuducu maye',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/04202.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Brake Fluid DOT 4",
    "price": [
      '400qr - 6 azn',
    ],
    'type': 'Əyləc mayesi',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/04006.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Aerosol quick clearner xt",
    "price": [
      '400qr - 6 azn',
    ],
    'type': 'Təmizləmə mayesi',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/40014.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Agrifluid HT",
    "price": [
      '20L - 200 azn',
    ],
    'type': 'Hidravlika yağı',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/34223.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Multi purpose greaz",
    "price": [
      '400qr - 6 azn',
    ],
    'type': '**',
    'image': '',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Air1 adblue",
    "price": [
      '10L - 33 azn',
    ],
    'type': 'Reagent',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/33428.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Cleansol",
    "price": [
      '30L - 170 azn',
    ],
    'type': 'Yağdan təmizləyici',
    'image': 'https://api.kroon-oil.com/img/web/part/560x560/13039.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Universal cleaner A",
    "price": [
      '30L - 200 azn',
    ],
    'type': '**',
    'image': '',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Universal Greas st q7",
    "price": [
      '400qr - 9 azn',
    ],
    'type': '**',
    'image': '',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "High Grease HT Q9",
    "price": [
      '400qr - 10 azn',
    ],
    'type': '**',
    'image': '',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
];

List priorPrice = [
  {
    "name": "Synthol 0w40",
    "price": [
      '1L - 16 azn',
      '4L - 60 azn',
      '5L - 72 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'http://prior-oil.com/img/products/35782.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Synthol 5w30",
    "price": [
      '1L - 12 azn',
      '4L - 45 azn',
      '5L - 55 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'http://prior-oil.com/img/products/2014-08-16-13295735523.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Synthol 5w40",
    "price": [
      '1L - 10 azn',
      '4L - 40 azn',
      '5L - 47 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'http://prior-oil.com/img/products/35536.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Gold Synthetic 10w40",
    "price": [
      '1L - 9 azn',
      '4L - 32 azn',
      '5L - 40 azn',
      '7L - 48 azn',
      '20L - 130 azn',
      '60L - 380 azn',
      '208L - 1250 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'http://prior-oil.com/img/products/35789.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Universal 15w40",
    "price": [
      '1L - 6 azn',
      '4L - 22 azn',
      '5L - 27 azn',
      '7L - 36 azn',
      '20L - 115 azn',
      '60L - 260 azn',
      '208L - 850 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'http://prior-oil.com/img/products/2014-08-16-15295635548.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Extra 20w50",
    "price": [
      '1L - 6 azn',
      '4L - 22 azn',
      '5L - 27 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'http://prior-oil.com/img/products/2014-08-16-15575435555.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "ATF Full Tronic",
    "price": [
      '1L - 15 azn',
      '4L - 55 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': '',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "ATF Super Tronic",
    "price": [
      '1L - 14 azn',
      '4L - 50 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': '',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Trancmatic ATF-II",
    "price": [
      '1L - 7 azn',
      '5L - 34 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'http://prior-oil.com/img/products/35590.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Trancmatic ATF-III",
    "price": [
      '1L - 10 azn',
      '5L - 47 azn',
    ],
    'type': 'Sürmət qutusu yağı',
    'image': 'http://prior-oil.com/img/products/35593.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Power Turbo Dizel 15w40",
    "price": [
      '5L - 32 azn',
      '7L - 41 azn',
      '20L - 120 azn',
      '60L - 340 azn',
      '208L - 1250 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'http://prior-oil.com/img/products/35775.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Telex HLP-46",
    "price": [
      '20L - 127 azn',
    ],
    'type': 'Hidravlika yağı',
    'image': 'http://prior-oil.com/img/products/35596.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Telex HVLP-68",
    "price": [
      '20L - 130 azn',
    ],
    'type': 'Hidravlika yağı',
    'image': 'http://prior-oil.com/img/products/2014-08-18-13004035599.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Dizel Turbo Ultra 10w40",
    "price": [
      '1L - 8 azn',
      '5L - 39 azn',
      '20L - 140 azn',
      '60L - 400 azn',
      '208L - 1350 azn',
    ],
    'type': 'Mühərrik yağı',
    'image': 'http://prior-oil.com/img/products/35562.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Antifreeze Arctic-40",
    "price": [
      '1L - 6 azn',
      '5L - 28 azn',
    ],
    'type': 'Soyuducu maye',
    'image': 'http://prior-oil.com/img/products/35602.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
  {
    "name": "Brakefluid DOT-4",
    "price": [
      '250qr - 4 azn',
    ],
    'type': 'Əyləc mayesi',
    'image': 'http://prior-oil.com/img/products/2014-08-27-03093535619.png',
    'characteristic': '',
    'description': '',
    'use': '',
    'test': '',
  },
];
